import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({...(process.env.AQUARIUM_CHROME?{executablePath:process.env.AQUARIUM_CHROME}:{}),headless:true,args:['--no-sandbox']});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 await page.goto((process.env.AQUARIUM_URL||'http://127.0.0.1:8765'));await page.waitForFunction(()=>window.aquarium?.worlds[0]);assert.equal(await page.locator('.plan-button').count(),10);
 await page.locator('#tab-alternate').click();assert.equal(await page.locator('.plan-button').count(),3);const results=[];
 for(let i=0;i<3;i++){
  await page.locator('.plan-button').nth(i).click();const s=await page.evaluate(()=>window.aquarium.snapshot());assert.equal(s.counts[0],[18,26,30][i]);assert.equal(s.catalog,'alternate');assert.ok(await page.locator('#alternate-warning').isVisible());
  await page.locator('#pause').click();for(const stage of ['starter','established']){await page.locator(`[data-stage=${stage}]`).click();await page.locator('#canvas-a').screenshot({path:`validation/alternate-${i+1}-${stage}.png`});}await page.locator('#pause').click();
  for(const href of await page.locator('#plan-notes a').evaluateAll(as=>as.map(a=>a.href)))assert.equal((await page.request.get(href)).status(),200,href);results.push(s);
 }
 await page.locator('.plan-button').nth(1).click();assert.match(await page.locator('#details').innerText(),/Needs quote/);assert.match(await page.locator('#details').innerText(),/Not reassessed/);
 await page.locator('#favorite').click();await page.locator('#note').fill('Alternative test: bottom fish');await page.reload();await page.waitForFunction(()=>window.aquarium?.worlds[0]);await page.locator('#tab-alternate').click();await page.locator('.plan-button').nth(1).click();assert.equal(await page.locator('#favorite').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#note').inputValue(),'Alternative test: bottom fish');
 await page.locator('#compare').click();await page.locator('#plan-b').selectOption('upper-paraguay-bodoquena-community');const compared=await page.evaluate(()=>window.aquarium.snapshot());assert.deepEqual(compared.counts,[26,20]);assert.equal(await page.evaluate(()=>window.aquarium.worlds[0].time===window.aquarium.worlds[1].time),true);await page.screenshot({path:'validation/alternate-paraguay-comparison.png',fullPage:true});await page.locator('#compare').click();
 const [download]=await Promise.all([page.waitForEvent('download',{timeout:90000}),page.locator('#export-all').click()]);assert.equal(download.suggestedFilename(),'aquarium-alternate-habitats.png');await download.saveAs('validation/export-alternates.png');
 await page.locator('#tab-main').click();assert.equal(await page.locator('.plan-button').count(),10);assert.equal(await page.locator('#alternate-warning').isVisible(),false);await page.locator('#tab-main').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tab-alternate').evaluate(e=>e===document.activeElement),true);
 await page.setViewportSize({width:768,height:1024});await page.screenshot({path:'validation/alternate-tablet.png',fullPage:true});
 const floorCheck=await page.evaluate(async()=>{const THREE=await import('/vendor/three.module.js'),{FishModel}=await import('/src/fish-model.js'),s=window.aquarium.adapter.species.get('Osteogaster aenea'),L=s.totalLengthCm,a={id:0,species:s,sex:'male',position:[0,0,0],heading:0,pitch:0,velocity:[L*s.profile.speed,0,0],phase:0,display:1},m=new FishModel(a);let minY=Infinity;for(const pitch of [-s.profile.pitchLimit,s.profile.pitchLimit])for(let phase=0;phase<32;phase++){a.pitch=pitch;a.phase=phase*.7;m.update(phase*.29);m.root.updateMatrixWorld(true);m.root.traverse(o=>{if(!o.geometry)return;const pos=o.geometry.attributes.position;for(let i=0;i<pos.count;i++){const v=new THREE.Vector3().fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld);minY=Math.min(minY,v.y);}});}m.dispose();return{minY,clearance:L*s.profile.floorClearanceFraction};});assert.ok(-floorCheck.minY<floorCheck.clearance);
 assert.deepEqual(errors,[]);await fs.writeFile('validation/alternate-browser-results.json',JSON.stringify({date:new Date().toISOString(),results,compared,floorCheck,errors,verified:['accessible separate tabs','three exact cohorts','both stages','source links','unknown cory costs/work','favorites/notes persistence','cross-collection comparison','alternate-only PNG export','main ten preserved','keyboard navigation','tablet layout','cory floor mesh bound']},null,2));console.log('Three alternates verified; no browser errors.');
}finally{await browser.close();}
