import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({...(process.env.AQUARIUM_CHROME?{executablePath:process.env.AQUARIUM_CHROME}:{}),headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});const errors=[],failedRequests=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('requestfailed',r=>failedRequests.push(r.url()));
const state=()=>page.evaluate(()=>window.aquarium.snapshot());
await page.goto((process.env.AQUARIUM_URL||'http://127.0.0.1:8765'));await page.waitForFunction(()=>window.aquarium?.worlds[0]);assert.equal((await state()).plans,10);await page.waitForTimeout(4000);
const records=[];for(let i=0;i<10;i++){
 await page.locator('.plan-button').nth(i).click();await page.waitForTimeout(650);const s=await state(),p=await page.evaluate(()=>window.aquarium.adapter.get(window.aquarium.snapshot().selected));assert.equal(s.counts[0],p.fishCount);assert.equal(s.counts.length,1);assert.equal(await page.locator('.plan-button[aria-pressed=true]').count(),1);await page.screenshot({path:`validation/${String(i+1).padStart(2,'0')}-established.png`,fullPage:true});await page.locator('#canvas-a').screenshot({path:`validation/${String(i+1).padStart(2,'0')}-scene.png`});records.push({...s,planName:p.name});
 await page.locator('[data-stage=starter]').click();await page.waitForTimeout(150);assert.equal((await state()).counts[0],p.fishCount);await page.locator('#canvas-a').screenshot({path:`validation/${String(i+1).padStart(2,'0')}-starter.png`});await page.locator('[data-stage=established]').click();
}
await page.locator('.plan-button').nth(1).click();assert.equal((await state()).counts[0],10);assert.equal(await page.evaluate(()=>window.aquarium.worlds[0].agents.every(a=>a.species.profile.mark==='gold')),true);
await page.locator('#pause').click();const click=await page.evaluate(async()=>{const THREE=await import('/vendor/three.module.js');const r=window.aquarium.renderers[0],a=window.aquarium.worlds[0].agents[0],p=new THREE.Vector3(...a.position).project(r.camera),rect=r.renderer.domElement.getBoundingClientRect();return {x:rect.left+(p.x*.5+.5)*rect.width,y:rect.top+(-p.y*.5+.5)*rect.height};});await page.mouse.click(click.x,click.y);assert.equal(await page.locator('#inspect').isVisible(),true);await page.locator('#inspect button').click();const time=await page.evaluate(()=>window.aquarium.worlds[0].time);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.aquarium.worlds[0].time),time);await page.locator('#labels').check();await page.locator('#scale').check();assert.equal(await page.locator('.fish-label').count(),10);await page.locator('#reset').click();assert.equal(await page.evaluate(()=>window.aquarium.worlds[0].time),0);await page.keyboard.press('Space');assert.equal((await state()).paused,false);
for(const [key,view] of [['2','orbit'],['3','top'],['1','front']]){await page.keyboard.press(key);assert.equal(await page.evaluate(()=>window.aquarium.session.view),view);}
await page.locator('#favorite').click();await page.locator('#note').fill('The gold school against fern leaves.');await page.reload();await page.waitForFunction(()=>window.aquarium?.worlds[0]);await page.locator('.plan-button').nth(1).click();assert.equal(await page.locator('#favorite').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#note').inputValue(),'The gold school against fern leaves.');
await page.locator('#compare').click();await page.locator('#plan-b').selectOption('araguaia-ember-chain-sword-margin');await page.waitForTimeout(1000);const comparison=await page.evaluate(()=>({snapshot:window.aquarium.snapshot(),times:window.aquarium.worlds.map(w=>w.time),cameras:window.aquarium.renderers.map(r=>r.camera.position.toArray())}));assert.deepEqual(comparison.snapshot.counts,[10,21]);assert.equal(comparison.times[0],comparison.times[1]);assert.deepEqual(comparison.cameras[0],comparison.cameras[1]);const box=await page.locator('#canvas-a').boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.57,box.y+box.height*.54,{steps:8});await page.mouse.up();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>window.aquarium.renderers[0].camera.position.distanceTo(window.aquarium.renderers[1].camera.position)<.0001),true);await page.locator('[data-view=front]').click();await page.screenshot({path:'validation/comparison.png',fullPage:true});
let [download]=await Promise.all([page.waitForEvent('download'),page.locator('#export').click()]);await download.saveAs('validation/export-comparison.png');assert.ok((await fs.stat('validation/export-comparison.png')).size>10000);
[download]=await Promise.all([page.waitForEvent('download',{timeout:90000}),page.locator('#export-all').click()]);await download.saveAs('validation/export-contact-sheet.png');assert.ok((await fs.stat('validation/export-contact-sheet.png')).size>50000);
await page.locator('#geometry-open').click();await page.locator('[name=length]').fill('85');await page.locator('#geometry-form [type=submit]').click();assert.equal((await state()).geometry.length,85);assert.deepEqual((await state()).counts,[10,21]);assert.equal(await page.locator('#space-warning').isVisible(),true);await page.locator('#geometry-open').click();await page.locator('[name=length]').fill('90');await page.locator('#geometry-form [type=submit]').click();
const perf=[];for(const quality of ['high','economy']){await page.locator('#quality').selectOption(quality);await page.waitForTimeout(10000);perf.push(await page.evaluate(()=>({...window.aquarium.snapshot(),glRenderer:(()=>{const gl=window.aquarium.renderers[0].renderer.getContext(),x=gl.getExtension('WEBGL_debug_renderer_info');return x?gl.getParameter(x.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);})()})));}
await page.locator('#compare').click();await page.setViewportSize({width:768,height:1024});await page.waitForTimeout(250);await page.screenshot({path:'validation/tablet.png',fullPage:true});const links=await page.locator('#plan-notes a').evaluateAll(as=>as.map(a=>a.href));for(const link of links)assert.equal((await page.request.get(link)).status(),200,link);
assert.deepEqual(errors,[]);assert.deepEqual(failedRequests,[]);await fs.writeFile('validation/browser-results.json',JSON.stringify({date:new Date().toISOString(),browserVersion:browser.version(),viewport:[1440,1100],allPlans:records,comparison,rollingFrameCadenceAfterExport:perf,performanceMethodNote:"Rolling intervals include initialization/export stalls; use performance-results.json for separately counted warmed-up render windows.",errors,failedRequests,verified:['exact all-ten counts','both planting stages','Hainan golden replacement','pause/reset','labels/scale','keyboard views','favorite/note persistence','matched comparison time/camera','real PNG and contact-sheet exports','editable dimensions and space warning','tablet preview','source links']},null,2));console.log(JSON.stringify({errors,plans:records.length,performance:perf.map(s=>({quality:s.stats[0].quality,fps:s.fps,renderMs:s.stats.map(r=>r.renderMs),device:s.glRenderer})),exports:'verified'},null,2));await browser.close();
