import {PlanAdapter,TankGeometry,SimulationWorld,ComparisonSession} from './core.js';
import {AquariumRenderer} from './renderer.js';
const $=id=>document.getElementById(id),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const [config,manifest]=await Promise.all(['data/config.json','data/plans.json'].map(p=>fetch(p).then(r=>{if(!r.ok)throw new Error(`Could not load ${p}`);return r.json();})));
const adapter=new PlanAdapter(manifest),session=new ComparisonSession(config);let current=adapter.get(config.ui.defaultPlanId),second=adapter.plans.find(p=>p.id!==current.id),comparing=false,rendererA,rendererB,worldA,worldB,quality=config.rendering.defaultQuality,notes={},storage={};
try{storage=JSON.parse(localStorage.getItem(config.ui.storageKey)||'{}');session.favoriteIds=(storage.favorites||[]).filter(id=>adapter.plans.some(p=>p.id===id));notes=storage.notes||{};if(storage.geometry)session.geometry=new TankGeometry(storage.geometry);}catch{}
function save(){try{localStorage.setItem(config.ui.storageKey,JSON.stringify({favorites:session.favoriteIds,notes,geometry:session.geometry}));}catch{toast('Your browser could not save preferences locally.');}}
let toastTimer;function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3800);}
function inspect(a){$('inspect').innerHTML=`<button aria-label="Close fish details">×</button><strong>${escape(a.species.commonName)}</strong><em>${escape(a.species.scientificName)}</em><span>${a.species.totalLengthCm.toFixed(1)} cm adult visual allowance · ${escape(a.state)}</span>`;$('inspect').hidden=false;$('inspect').querySelector('button').onclick=()=>$('inspect').hidden=true;}
function world(plan){return new SimulationWorld(plan,session.geometry,adapter,config,session.stage,session.seed);}
function loadScenes(){try{const a=world(current),b=comparing?world(second):null;worldA=a;worldB=b;rendererA.load(a,session.view);if(b){if(!rendererB){rendererB=new AquariumRenderer($('canvas-b'),config,inspect);syncControls();}rendererB.setQuality(quality);rendererB.load(b,session.view);rendererB.syncFrom(rendererA);}else if(rendererB){rendererB.dispose();rendererB=null;}rendererA.setQuality(quality);$('inspect').hidden=true;render();return true;}catch(e){toast(e.message);return false;}}
let synchronizing=false;function syncControls(){for(const [source,target] of [[rendererA,()=>rendererB],[rendererB,()=>rendererA]]){if(source.syncListener)source.controls.removeEventListener('change',source.syncListener);source.syncListener=()=>{if(!comparing||synchronizing||!target())return;synchronizing=true;target().syncFrom(source);synchronizing=false;};source.controls.addEventListener('change',source.syncListener);}}
function planList(){const list=$('plan-list');list.replaceChildren();for(const plan of adapter.plans){const button=document.createElement('button');button.className='plan-button'+(plan.id===current.id?' active':'');button.dataset.planId=plan.id;button.setAttribute('aria-pressed',String(plan.id===current.id));button.innerHTML=`<span class="plan-number">${String(plan.number).padStart(2,'0')}</span><span class="plan-text"><strong>${escape(plan.name)}</strong><small>${plan.fishCount} fish · ${plan.groups.length} ${plan.groups.length===1?'species':'species'}</small></span><span class="plan-star">${session.favoriteIds.includes(plan.id)?'♥':''}</span>`;button.onclick=()=>selectPlan(plan);list.append(button);}updateFavorites();}
function updateFavorites(){const yes=session.favoriteIds.includes(current.id);$('favorite').textContent=yes?'♥ Saved favorite':'♡ Save favorite';$('favorite').setAttribute('aria-pressed',String(yes));$('favorites-count').textContent=`${session.favoriteIds.length} saved`;}
function selectPlan(plan){const old=current;current=plan;if(!loadScenes()){current=old;$('plan-a').value=old.id;return;}planList();updateDetails();$('plan-a').value=current.id;}
function updateDetails(){const t=session.geometry,plan=current,c=t.constraints(plan);$('scene-title').textContent=comparing?'Two habitats, one view':plan.name;$('scene-region').textContent=comparing?'COMPARE YOUR FAVORITES':`${plan.country} · ${plan.displayHabitat}`;$('caption-a').textContent=`${plan.fishCount} ADULT FISH · ${session.stage==='starter'?'STARTER':'ESTABLISHED'} PLANTING`;$('caption-a').hidden=comparing;$('plan-a').hidden=!comparing;
 $('plant-note').textContent=session.stage==='established'?'*Illustrative established growth, not a guaranteed outcome.':'Starter nursery quantities; shoot count and cover are illustrative.';
 const money=p=>`$${p.startupUsd.toFixed(2)}`,maintenance=p=>`${Math.round(p.maintenance.low)}–${Math.ceil(p.maintenance.high)} min/week`;
 const species=p=>p.groups.map(g=>`<li><span class="fish-swatch" style="background:${adapter.species.get(g.species).profile.color}"></span>${g.count} ${escape(adapter.species.get(g.species).commonNamePlural.toLowerCase())}</li>`).join('');
 if(comparing){$('details').innerHTML=`<div><div class="detail-label">${escape(plan.name)}</div><ul class="species-list">${species(plan)}</ul><div class="detail-sub">${money(plan)} conditional · ${maintenance(plan)}</div></div><div class="detail-compare"><div class="detail-label">${escape(second.name)}</div><ul class="species-list">${species(second)}</ul><div class="detail-sub">${money(second)} conditional · ${maintenance(second)}</div></div><div><div class="detail-label">A fair comparison</div><div class="detail-value">Same setting.</div><div class="detail-sub">Adult scale, camera, light and planting stage are matched.</div></div>`;}else{$('details').innerHTML=`<div><div class="detail-label">Your ${plan.fishCount} fish</div><ul class="species-list">${species(plan)}</ul></div><div><div class="detail-label">Complete startup estimate</div><div class="detail-value">${money(plan)}</div><div class="detail-sub">Conditional retail estimate · ${escape(manifest.sourceAccessedAt)}</div></div><div><div class="detail-label">Ordinary care</div><div class="detail-value">${maintenance(plan).replace(' min/week',' min')}</div><div class="detail-sub">per week, including periodic work</div></div>`;}
 const failures=[plan,...(comparing?[second]:[])].filter(p=>!t.constraints(p).baseFits||!t.constraints(p).laneFits);$('space-warning').hidden=!failures.length;$('space-warning').textContent=failures.map(p=>`${p.name}: this preview is below the planned ${t.constraints(p).required}.`).join(' ')+' Fish counts and tank size have not been changed to hide the constraint.';
 $('geometry-summary').textContent=`${t.length} × ${t.width} × ${t.height} cm · ${t.status==='measured'?'entered measurements':'assumed preview'}`;
 const range=x=>Array.isArray(x)?x.join('–'):x??'check source';const notesFor=p=>`<h3>${escape(p.name)} · plants and layout</h3><p>${p.plants.map(g=>`${g.quantity} ${escape(g.unit)} of <em>${escape(g.species)}</em>: ${escape(g.placement)}.`).join(' ')}</p><p>${p.substrate.massLb} lb of funded sand; ${p.substrate.patchDepthCm?`${p.substrate.patchDepthCm} cm planted patches with a shallower front`:'a shallow decorative layer'}. No added baseline wood, rocks or filler plants.</p><p>Space requirement: ${escape(t.constraints(p).required)}. ${escape(t.constraints(p).note)}</p><p>Regular stand scenario: ${p.regularStandUsd?`$${p.regularStandUsd.toFixed(2)}${p.regularStandUsd>manifest.ownerProfile.upfrontBudgetUsd?' — exceeds the saved retail ceiling':''}`:'see source assessment'}.</p><p>Appearance: ${p.groups.map(g=>escape(adapter.species.get(g.species).appearance)).join(' ')}</p><h3>Checks before choosing stocking</h3><p>Proposed water scenario: ${escape(range(p.environment.temperature_c))}°C · pH ${escape(range(p.environment.ph))} · GH ${escape(range(p.environment.gh_dgh))} dGH. Actual tap values and stability remain unknown.</p><ul><li>Measure tank space and seasonal temperature; preserve the planned clear lane and refuges.</li><li>Confirm ordinary food acceptance, healthy stock and low-tech plant establishment.</li><li>Check fitted filtration, heater, light, lid and support.</li><li>Requote the complete delivered retail setup, including any necessary receiving or isolation costs.</li></ul><a href="/references/habitat-options/${encodeURI(p.planFile)}" target="_blank">Public stocking snapshot ↗</a><a href="/references/habitat-options/${encodeURI(p.reportFile)}" target="_blank">Saved cost/work snapshot ↗</a>`;
 $('plan-notes').innerHTML=notesFor(plan)+(comparing?notesFor(second):'')+'<h3>About this preview</h3><p>Numerical swimming behavior, exact colors/sex mix and plant biomass are illustrative. Standard/body lengths are normalized separately from total length. Mature growth is not a promise. No simulation of water quality, breeding or compatibility is claimed. All underlying stocking assessments remain conditional.</p><a href="docs/provenance.md" target="_blank">Visual assumptions and asset provenance ↗</a>';
 $('note').value=notes[plan.id]||'';updateFavorites();}
function render(){if(!worldA)return;rendererA.render(worldA.time,session);if(comparing&&rendererB)rendererB.render(worldB.time,session);$('scale-note').textContent=session.scale?`Scale bar: ${rendererA.scaleLength.toFixed(1)} cm · adult proportions`:'Drag to look around · scroll to zoom · click a fish';}
let last=performance.now(),lastRender=0;const frames=[];function animate(now){const delta=(now-last)/1000;last=now;if(!session.paused&&!document.hidden){worldA?.advance(delta);worldB?.advance(delta);}const limit=1000/config.rendering[quality].fpsLimit;if(now-lastRender>=limit-.7){if(lastRender)frames.push(now-lastRender);if(frames.length>240)frames.shift();lastRender=now;render();}requestAnimationFrame(animate);}
function setView(view){session.view=view;rendererA.preset(view);rendererB?.syncFrom(rendererA);document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});render();}
function setStage(stage){const old=session.stage;session.stage=stage;if(!loadScenes()){session.stage=old;return;}document.querySelectorAll('[data-stage]').forEach(b=>{b.classList.toggle('active',b.dataset.stage===stage);b.setAttribute('aria-pressed',String(b.dataset.stage===stage));});updateDetails();}
function togglePause(){session.paused=!session.paused;$('pause').textContent=session.paused?'▷':'Ⅱ';$('pause').setAttribute('aria-label',session.paused?'Resume swimming':'Pause swimming');$('play-status').textContent=session.paused?'Paused for a closer look':'Swimming live';render();}
function download(data,name){const a=document.createElement('a');a.href=data;a.download=name;a.click();}
async function exportImage(){render();const images=await Promise.all([rendererA,...(comparing?[rendererB]:[])].map(r=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(i);i.src=r.capture();})));const c=document.createElement('canvas');c.width=images.reduce((n,i)=>n+i.width,0);c.height=Math.max(...images.map(i=>i.height))+90;const ctx=c.getContext('2d');ctx.fillStyle='#f7f6f0';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#2b4736';ctx.font='22px Georgia';ctx.fillText('Aquarium Studio · Adult-scale habitat preview',24,32);let x=0;images.forEach((i,n)=>{ctx.drawImage(i,x,52);ctx.font='15px sans-serif';ctx.fillText((n?second:current).name,x+15,c.height-13);x+=i.width;});download(c.toDataURL(),'aquarium-'+(comparing?'comparison':current.id)+'.png');toast('Image saved.');}
async function exportAll(){const button=$('export-all');button.disabled=true;toast('Preparing all ten habitats…');const holder=document.createElement('div');holder.style.cssText='position:fixed;left:-3000px;top:0;width:700px;height:380px';document.body.append(holder);let preview;try{preview=new AquariumRenderer(holder,config,()=>{});preview.setQuality('economy');const canvas=document.createElement('canvas');canvas.width=1400;canvas.height=5*440+65;const ctx=canvas.getContext('2d');ctx.fillStyle='#f7f6f0';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#334e3a';ctx.font='25px Georgia';ctx.fillText('Ten habitats · '+session.stage+' planting · adult scale',24,36);for(let n=0;n<adapter.plans.length;n++){const p=adapter.plans[n],w=world(p);for(let i=0;i<240;i++)w.step(config.simulation.fixedStep);preview.load(w,session.view);preview.render(w.time,session);ctx.drawImage(preview.renderer.domElement,n%2*700,65+Math.floor(n/2)*440,700,380);ctx.fillStyle='#334e3a';ctx.font='18px Georgia';ctx.fillText(`${String(n+1).padStart(2,'0')}  ${p.name}`,n%2*700+20,65+Math.floor(n/2)*440+405);ctx.font='12px sans-serif';ctx.fillText(`${p.fishCount} fish · $${p.startupUsd.toFixed(2)} conditional · illustrative movement/growth`,n%2*700+20,65+Math.floor(n/2)*440+425);await new Promise(r=>setTimeout(r,0));}download(canvas.toDataURL(),'aquarium-ten-habitats.png');toast('All ten habitats saved.');}catch(e){toast(e.message);}finally{preview?.dispose();holder.remove();button.disabled=false;}}
for(const [name,bounds] of Object.entries(config.ui.dimensionInputBounds)){const input=$('geometry-form').elements.namedItem(name);input.min=bounds[0];input.max=bounds[1];}
$('quality').value=quality;$('labels').checked=session.labels;$('scale').checked=session.scale;for(const type of ['view','stage'])document.querySelectorAll(`[data-${type}]`).forEach(button=>{const active=button.dataset[type]===session[type];button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});
try{rendererA=new AquariumRenderer($('canvas-a'),config,inspect);$('loading').remove();for(const select of [$('plan-a'),$('plan-b')])for(const p of adapter.plans){const opt=document.createElement('option');opt.value=p.id;opt.textContent=p.name;select.append(opt);}$('plan-a').value=current.id;$('plan-b').value=second.id;loadScenes();planList();updateDetails();requestAnimationFrame(animate);}catch(e){$('loading').textContent='The preview could not start. Check WebGL support and the local server.';console.error(e);}
$('favorite').onclick=()=>{const idx=session.favoriteIds.indexOf(current.id);if(idx<0)session.favoriteIds.push(current.id);else session.favoriteIds.splice(idx,1);save();planList();};$('note').oninput=()=>{notes[current.id]=$('note').value;save();};
$('compare').onclick=()=>{comparing=!comparing;$('compare').setAttribute('aria-pressed',String(comparing));$('compare').textContent=comparing?'Leave comparison':'Compare two';$('scenes').classList.toggle('comparing',comparing);document.querySelector('.compare-panel').hidden=!comparing;loadScenes();updateDetails();rendererA.resize();rendererB?.resize();};
$('plan-a').onchange=e=>selectPlan(adapter.get(e.target.value));$('plan-b').onchange=e=>{const old=second;second=adapter.get(e.target.value);if(!loadScenes()){second=old;$('plan-b').value=old.id;}updateDetails();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>setStage(b.dataset.stage));$('pause').onclick=togglePause;$('reset').onclick=()=>{loadScenes();toast('Same seed, a fresh start.');};$('labels').onchange=e=>{session.labels=e.target.checked;render();};$('scale').onchange=e=>{session.scale=e.target.checked;render();};$('quality').onchange=e=>{quality=e.target.value;rendererA.setQuality(quality);rendererB?.setQuality(quality);};$('export').onclick=exportImage;$('export-all').onclick=exportAll;
$('geometry-open').onclick=()=>{const form=$('geometry-form');for(const k of ['length','width','height','waterline'])form.elements.namedItem(k).value=session.geometry[k];form.elements.namedItem('measured').checked=session.geometry.status==='measured';$('geometry-dialog').showModal();};$('geometry-cancel').onclick=()=>$('geometry-dialog').close();$('geometry-form').onsubmit=e=>{e.preventDefault();const form=e.target;const old=session.geometry;try{session.geometry=new TankGeometry({...session.geometry,...Object.fromEntries(['length','width','height','waterline'].map(k=>[k,Number(form.elements.namedItem(k).value)])),status:form.elements.namedItem('measured').checked?'measured':'assumed'});if(!loadScenes()){session.geometry=old;loadScenes();return;}save();updateDetails();$('geometry-dialog').close();}catch(error){session.geometry=old;toast(error.message);}};
$('help').onclick=()=>toast('Space: pause · R: reset · F: favorite · 1/2/3: front/angle/top · +/−: zoom · arrows: orbit');document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||$('geometry-dialog').open)return;if(e.code==='Space'){e.preventDefault();togglePause();}if(e.key.toLowerCase()==='r')$('reset').click();if(e.key.toLowerCase()==='f')$('favorite').click();const view={'1':'front','2':'orbit','3':'top'}[e.key];if(view)setView(view);if(['+','=','-','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const cam=rendererA.camera,target=rendererA.controls.target,offset=cam.position.clone().sub(target);if(['+','=','-'].includes(e.key)){offset.multiplyScalar(e.key==='-'?1.12:.89);const length=offset.length();offset.multiplyScalar(Math.min(rendererA.controls.maxDistance,Math.max(rendererA.controls.minDistance,length))/length);}else{const az=e.key==='ArrowLeft'?.09:e.key==='ArrowRight'?-.09:0;offset.applyAxisAngle({x:0,y:1,z:0},az);if(e.key==='ArrowUp')offset.y+=3;if(e.key==='ArrowDown')offset.y-=3;}cam.position.copy(target).add(offset);rendererA.controls.update();rendererB?.syncFrom(rendererA);render();}});
// Read-only diagnostic evidence for local validation; no automatic suitability changes.
window.aquarium={adapter,session,config,selectPlan:id=>selectPlan(adapter.get(id)),setStage,setView,get worlds(){return [worldA,...(comparing?[worldB]:[])];},get renderers(){return [rendererA,...(comparing?[rendererB]:[])];},snapshot:()=>({plans:adapter.plans.length,selected:current.id,comparison:comparing,geometry:{...session.geometry},stage:session.stage,paused:session.paused,counts:[worldA?.agents.length,worldB?.agents.length].filter(x=>x!==undefined),stats:[rendererA?.stats(),rendererB?.stats()].filter(Boolean),fps:frames.length?1000/(frames.reduce((s,x)=>s+x,0)/frames.length):null})};
