import * as THREE from 'three';
import {describePlant} from './plant-layout.js';
import {Random} from './core.js';
function blade(form,segments){const g=new THREE.BufferGeometry(),pos=[],uv=[],idx=[];for(let i=0;i<=segments;i++){const t=i/segments;let w=Math.sin(Math.PI*t)*.5;if(form==='grass')w=.13*Math.pow(1-t,.4);if(form==='needle')w=.055*Math.sin(Math.PI*t);if(form==='fern')w*=.68+.32*Math.sin(t*Math.PI*10)**2;for(let s=0;s<2;s++){pos.push((s?1:-1)*w,t,Math.sin(t*Math.PI)*.10+(s?.025:0));uv.push(s,t);}if(i<segments){const a=i*2;idx.push(a,a+1,a+2,a+1,a+3,a+2);}}g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g;}
function leafTexture(){const c=document.createElement('canvas');c.width=64;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#a5b47e';ctx.fillRect(0,0,64,128);const g=ctx.createLinearGradient(0,0,64,0);g.addColorStop(0,'#718651');g.addColorStop(.5,'#b7c38b');g.addColorStop(1,'#758851');ctx.fillStyle=g;ctx.fillRect(0,0,64,128);ctx.strokeStyle='rgba(64,97,37,.3)';ctx.lineWidth=1;for(let y=7;y<128;y+=10){ctx.beginPath();ctx.moveTo(32,y);ctx.lineTo(2,y+14);ctx.moveTo(32,y);ctx.lineTo(62,y+14);ctx.stroke();}ctx.strokeStyle='rgba(180,199,126,.6)';ctx.beginPath();ctx.moveTo(32,0);ctx.lineTo(32,128);ctx.stroke();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
export class PlantGarden {
 constructor(layout,renderConfig){this.root=new THREE.Group();this.time={value:0};this.materials=[];const leaves=[],stems=[],roots=[];const obj=new THREE.Object3D();
 const add=(list,position,scale,rotation)=>{obj.position.set(...position);obj.scale.set(...scale);obj.rotation.set(...rotation);obj.updateMatrix();list.push(obj.matrix.clone());};
 for(const p of layout.patches){const description=p.structure||describePlant(p,new Random(p.seed));for(const leaf of description.leaves)add(leaves,leaf.position,leaf.scale,leaf.rotation);for(const root of description.roots)add(roots,root.position,root.scale,root.rotation);for(const stem of description.stems){if(stem.a){const a=new THREE.Vector3(...stem.a),b=new THREE.Vector3(...stem.b),delta=b.clone().sub(a);obj.position.copy(a.add(b).multiplyScalar(.5));obj.scale.set(stem.radius,delta.length(),stem.radius);obj.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());obj.updateMatrix();stems.push(obj.matrix.clone());}else add(stems,stem.position,stem.scale,stem.rotation);}}
 const form=layout.plan.plants[0].profile.form;
 const leafMat=new THREE.MeshStandardMaterial({color:layout.plan.plants[0].profile.color,map:leafTexture(),roughness:.83,emissive:layout.plan.plants[0].profile.color,emissiveIntensity:.18,side:THREE.DoubleSide});const stemMat=new THREE.MeshStandardMaterial({color:0x687947,roughness:1});const rootMat=new THREE.MeshStandardMaterial({color:0x8a8163,roughness:1});
 for(const mat of [leafMat,stemMat,rootMat]){mat.onBeforeCompile=s=>{s.uniforms.plantTime=this.time;s.vertexShader='uniform float plantTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <project_vertex>',`#include <project_vertex>\n`);s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\ntransformed.x+=sin(plantTime*${renderConfig.plantSwaySpeed.toFixed(3)}+position.y*0.5+instanceMatrix[3].x*0.12)*${renderConfig.plantSwayAmplitude.toFixed(3)}*position.y;`);};this.materials.push(mat);}
 const batches=[[leaves,blade(form==='fern'?'leaflet':['crypt','grass'].includes(form)?form:'needle',renderConfig.leafSegments[form==='fern'?'leaflet':['crypt','grass'].includes(form)?form:'needle']),leafMat],[stems,new THREE.CylinderGeometry(.5,.65,1,5),stemMat],[roots,new THREE.CylinderGeometry(.5,.3,1,4),rootMat]];
 for(const [list,geo,mat] of batches){if(!list.length)continue;const mesh=new THREE.InstancedMesh(geo,mat,list.length);list.forEach((m,i)=>mesh.setMatrixAt(i,m));mesh.userData.plantStructureKind=list===stems?"stem":list===roots?"root":"leaf";mesh.castShadow=true;mesh.receiveShadow=true;mesh.computeBoundingSphere();this.root.add(mesh);}
 }
 update(time){this.time.value=time;}
 dispose(){this.root.traverse(o=>{if(o.isInstancedMesh)o.dispose();o.geometry?.dispose();});this.materials.forEach(m=>{m.map?.dispose();m.dispose();});}
}
