import * as THREE from 'three';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {FishModel} from './fish-model.js';
import {FishSchool} from './fish-school.js';
import {PlantGarden} from './plants.js';
import {Random} from './core.js';
function sandTexture(){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),r=new Random(7);ctx.fillStyle='#d4cdb9';ctx.fillRect(0,0,256,256);for(let i=0;i<16000;i++){ctx.fillStyle=['#c9c0a9','#beb59d','#e0d8c6','#dad1bd','#aea790'][i%5];ctx.fillRect(r.next()*256,r.next()*256,r.range(.35,1.2),r.range(.35,1.2));}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(7,4);return t;}
function roundedBox(w,h,d,mat){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);}
export class AquariumRenderer {
 constructor(container,config,onSelect){this.container=container;this.config=config;this.onSelect=onSelect;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(config.rendering.background);const studio=new THREE.Scene();studio.background=new THREE.Color('#d5ddcf');for(const [x,y,z,w,h] of [[0,5,0,9,3],[-4,1,4,3,4],[5,2,-3,2,5]]){const panel=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({color:0xf8f4df,side:THREE.DoubleSide,forceSinglePass:true}));panel.position.set(x,y,z);panel.lookAt(0,0,0);studio.add(panel);}this.studio=studio;this.environmentGenerator=null;this.scene.fog=new THREE.FogExp2(0xdce3d9,.00055);this.renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,alpha:false,powerPreference:'high-performance'});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=config.rendering.exposure;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;const pmrem=new THREE.PMREMGenerator(this.renderer);this.environmentMap=pmrem.fromScene(studio,.04);this.scene.environment=this.environmentMap.texture;this.scene.environmentIntensity=config.rendering.environmentIntensity;pmrem.dispose();this.container.append(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','Interactive aquarium. Drag to orbit; scroll to zoom; click a fish to inspect.');this.renderer.domElement.tabIndex=0;
 this.camera=new THREE.PerspectiveCamera(config.camera.fov,1,.1,1500);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.09;this.controls.enablePan=false;this.controls.minPolarAngle=.001;this.controls.maxPolarAngle=Math.PI*.58;this.controls.minAzimuthAngle=-Math.PI*.8;this.controls.maxAzimuthAngle=Math.PI*.8;
 this.labels=document.createElement('div');this.labels.className='fish-labels';this.container.append(this.labels);this.labelNodes=[];this.raycaster=new THREE.Raycaster();let down;
 this.renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});this.renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=this.renderer.domElement.getBoundingClientRect();this.raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),this.camera);for(const batch of this.school?.batches||[])batch.mesh.computeBoundingSphere();const hit=this.raycaster.intersectObjects(this.school?[this.school.root]:[],true)[0];if(hit)this.onSelect(this.world.agents[hit.object.userData.agentIds[hit.instanceId]]);});
 this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(container);this.setQuality(config.rendering.defaultQuality);this.fish=[];this.scene.add(new THREE.HemisphereLight(0xe8f0dc,0x647565,2.4));const sun=new THREE.DirectionalLight(0xfff5d9,3.1);sun.position.set(-30,120,45);sun.castShadow=true;sun.shadow.camera.left=-110;sun.shadow.camera.right=110;sun.shadow.camera.top=80;sun.shadow.camera.bottom=-80;sun.shadow.bias=-.0005;sun.shadow.normalBias=.2;this.sun=sun;this.scene.add(sun);this.scene.add(new THREE.AmbientLight(0xa8c1b0,.25));this.selectLight=new THREE.PointLight(0xffffff,14,130);this.selectLight.position.set(15,35,70);this.scene.add(this.selectLight);this.frameTimes=[];
 }
 setQuality(q){this.quality=q;const cfg=this.config.rendering[q];this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,cfg.pixelRatioCap));this.renderer.transmissionResolutionScale=cfg.transmissionResolutionScale;if(this.sun){this.sun.shadow.mapSize.setScalar(cfg.shadowSize);this.sun.shadow.map?.dispose();this.sun.shadow.map=null;}this.resize();}
 resize(){const {width,height}=this.container.getBoundingClientRect();if(!width||!height)return;this.renderer.setSize(width,height);this.camera.aspect=width/height;this.camera.updateProjectionMatrix();}
 load(world,view){if(this.environment){this.scene.remove(this.environment);this.environment.traverse(o=>{if(o.isInstancedMesh)o.dispose();o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material]){m.map?.dispose();m.dispose();}}});}if(this.school){this.scene.remove(this.school.root);this.school.dispose();}for(const f of this.fish)f.dispose();this.garden?.dispose();this.environment=new THREE.Group();this.scene.add(this.environment);this.world=world;this.fish=world.agents.map(a=>new FishModel(a));this.school=new FishSchool(this.fish);this.scene.add(this.school.root);this.garden=new PlantGarden(world.layout,this.config.rendering);this.environment.add(this.garden.root);this.buildTank(world);this.labels.replaceChildren();this.labelNodes=world.agents.map(a=>{const el=document.createElement('span');el.className='fish-label';el.textContent=a.species.commonName;this.labels.append(el);return el;});this.resize();this.preset(view);}
 buildTank(world){const t=world.tank,l=world.layout,group=this.environment;const dark=new THREE.MeshStandardMaterial({color:0x303d35,roughness:.7});const black=new THREE.MeshStandardMaterial({color:0x394239,roughness:.75});const pale=new THREE.MeshStandardMaterial({color:0xe0dbcd,roughness:1});
 // Display plinth and surround are outside the aquarium, not invented underwater decor.
 const plinth=roundedBox(t.length+3,2,t.width+3,dark);plinth.position.y=-1.1;plinth.receiveShadow=true;group.add(plinth);const floor=new THREE.Mesh(new THREE.PlaneGeometry(1500,1500),pale);floor.rotation.x=-Math.PI/2;floor.position.y=-3;floor.receiveShadow=true;group.add(floor);
 const sandGeo=new THREE.PlaneGeometry(t.length,t.width,72,36);const pos=sandGeo.attributes.position;const r=new Random(42);for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=-pos.getY(i);pos.setZ(i,l.floorAt(x,z)+r.range(-.045,.045));}sandGeo.rotateX(-Math.PI/2);sandGeo.computeVertexNormals();const sand=new THREE.Mesh(sandGeo,new THREE.MeshStandardMaterial({map:sandTexture(),color:0xf3efdb,roughness:1}));sand.receiveShadow=true;group.add(sand);
 for(const s of l.decorSegments||[]){const a=new THREE.Vector3(...s.a),b=new THREE.Vector3(...s.b),mesh=new THREE.Mesh(new THREE.CylinderGeometry(s.r*.72,s.r,a.distanceTo(b),10),new THREE.MeshStandardMaterial({color:0x76634c,roughness:.97}));mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);}
 const sandSides=roundedBox(t.length,l.frontDepth,t.width,new THREE.MeshStandardMaterial({color:0xc9c2ad,roughness:1}));sandSides.position.y=l.frontDepth/2;group.add(sandSides);
 const edge=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(t.length,t.height,t.width)),new THREE.LineBasicMaterial({color:0x728d83,transparent:true,opacity:.4}));edge.position.y=t.height/2;group.add(edge);
 // Very light glass faces retain visibility while producing restrained highlights.
 const glassMat=new THREE.MeshPhysicalMaterial({color:0xe0eee4,transparent:true,opacity:this.config.rendering.glassOpacity,transmission:this.config.rendering.glassTransmission,thickness:t.glassThickness,ior:this.config.rendering.glassIor,roughness:.10,metalness:0,envMapIntensity:.35,side:THREE.DoubleSide,forceSinglePass:true,depthWrite:false});
 for(const side of [-1,1]){const face=new THREE.Mesh(new THREE.PlaneGeometry(t.width,t.height),glassMat);face.rotation.y=Math.PI/2;face.position.set(side*t.length/2,t.height/2,0);group.add(face);}const front=new THREE.Mesh(new THREE.PlaneGeometry(t.length,t.height),glassMat);front.position.set(0,t.height/2,t.width/2);group.add(front);const back=new THREE.Mesh(new THREE.PlaneGeometry(t.length,t.height),glassMat);back.position.set(0,t.height/2,-t.width/2);group.add(back);
 const waterGeo=new THREE.PlaneGeometry(t.length-.5,t.width-.5,40,20);waterGeo.rotateX(-Math.PI/2);const waterMat=new THREE.MeshPhysicalMaterial({color:0xbacdc1,transparent:true,opacity:.19,roughness:.23,metalness:.22,side:THREE.DoubleSide,forceSinglePass:true,depthWrite:false});const uni={value:0};waterMat.onBeforeCompile=s=>{s.uniforms.waterTime=uni;s.vertexShader='uniform float waterTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`#include <begin_vertex>\ntransformed.y+=sin(position.x*0.23+waterTime*1.2)*cos(position.z*0.27+waterTime*.6)*${this.config.rendering.surfaceWaveAmplitude};`);};this.waterTime=uni;const surface=new THREE.Mesh(waterGeo,waterMat);surface.position.y=t.waterline;group.add(surface);
 const waterEdge=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(t.length-.2,.04,t.width-.2)),new THREE.LineBasicMaterial({color:0x97b9ad,transparent:true,opacity:.55}));waterEdge.position.y=t.waterline;group.add(waterEdge);
 // Thin perimeter frame plus a mostly transparent fitted lid; no opaque display hood.
 const frame=roundedBox(t.length+1,.5,.7,dark);for(const z of [-t.width/2,t.width/2]){const f=frame.clone();f.position.set(0,t.height,z);group.add(f);}for(const x of [-t.length/2,t.length/2]){const f=roundedBox(.7,.5,t.width,dark);f.position.set(x,t.height,0);group.add(f);}
 const lid=new THREE.Mesh(new THREE.PlaneGeometry(t.length-1,t.width-1),new THREE.MeshPhysicalMaterial({color:0xe1e9dd,transparent:true,opacity:.035,side:THREE.DoubleSide,forceSinglePass:true,depthWrite:false}));lid.rotation.x=-Math.PI/2;lid.position.y=t.height;group.add(lid);
 const light=roundedBox(t.length*.76,.6,2.7,black);light.position.set(0,t.height+2,-t.width*.17);group.add(light);const led=roundedBox(t.length*.73,.1,1.5,new THREE.MeshBasicMaterial({color:0xeeeac7}));led.position.set(0,t.height+1.66,-t.width*.17);group.add(led);
 for(const e of l.equipment){const gear=new THREE.Group();gear.userData.equipmentType=e.type;group.add(gear);const tube=new THREE.Mesh(new THREE.CylinderGeometry(e.r,e.r,e.y1-e.y0,12),new THREE.MeshStandardMaterial({color:e.type==='heater'?0x818b75:e.type==='thermometer'?0xbdc6af:0x455c50,roughness:.4,metalness:.1}));tube.position.set(e.x,(e.y1+e.y0)/2,e.z);tube.castShadow=true;gear.add(tube);if(e.housingSizeCm){const box=roundedBox(...e.housingSizeCm,black);box.position.set(...e.housingCenter);gear.add(box);for(let j=0;j<6;j++){const ring=new THREE.Mesh(new THREE.TorusGeometry(e.r+.01,.12,4,12),dark);ring.rotation.x=Math.PI/2;ring.position.set(e.x,e.y0+j*.75,e.z);gear.add(ring);}}else if(e.capSizeCm){const cap=roundedBox(...e.capSizeCm,dark);cap.position.set(e.x,e.y1,e.z);gear.add(cap);}else if(e.type==='thermometer'){const bulb=new THREE.Mesh(new THREE.SphereGeometry(e.r*1.1,8,8),new THREE.MeshStandardMaterial({color:0xb88663,roughness:.5}));bulb.position.set(e.x,e.y0,e.z);gear.add(bulb);}}
 this.scaleGroup=new THREE.Group();group.add(this.scaleGroup);const len=t.length/4;const pts=[new THREE.Vector3(-len/2,-1,t.width/2+3),new THREE.Vector3(len/2,-1,t.width/2+3)];this.scaleGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x435c4d})));for(const x of [-len/2,len/2])this.scaleGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(x,-2,t.width/2+3),new THREE.Vector3(x,0,t.width/2+3)]),new THREE.LineBasicMaterial({color:0x435c4d})));this.scaleLength=len;
 }
 preset(name){if(!this.world)return;const t=this.world.tank,dir=new THREE.Vector3(...this.config.camera[name]).normalize();const right=new THREE.Vector3(0,1,0).cross(dir).normalize(),up=dir.clone().cross(right).normalize();const tanY=Math.tan(this.camera.fov*Math.PI/360),tanX=tanY*this.camera.aspect;let fit=0;for(const x of [-t.length/2-2,t.length/2+2])for(const y of [-2,t.height+3])for(const z of [-t.width/2-2,t.width/2+2]){const corner=new THREE.Vector3(x,y-t.height*.48,z);fit=Math.max(fit,corner.dot(dir)+Math.max(Math.abs(corner.dot(right))/tanX,Math.abs(corner.dot(up))/tanY));}const dist=fit*this.config.camera.distanceMultiplier;this.controls.target.set(0,t.height*.48,0);this.camera.position.copy(this.controls.target).addScaledVector(dir,dist);this.controls.minDistance=t.length*this.config.camera.minimumDistanceMultiplier;this.controls.maxDistance=t.length*this.config.camera.maximumDistanceMultiplier;this.controls.update();this.controls.saveState();}
 syncFrom(other){this.camera.position.copy(other.camera.position);this.camera.quaternion.copy(other.camera.quaternion);this.controls.target.copy(other.controls.target);this.controls.update();}
 render(time,{labels=false,scale=false}={}){if(!this.world)return;const start=performance.now();this.school.update(time);this.garden.update(time);this.waterTime.value=time;this.scaleGroup.visible=scale;this.controls.update();this.renderer.render(this.scene,this.camera);this.labels.hidden=!labels;
 if(labels){const rect=this.container.getBoundingClientRect();this.world.agents.forEach((a,i)=>{const p=new THREE.Vector3(...a.position);p.y+=a.species.totalLengthCm*.3;p.project(this.camera);const el=this.labelNodes[i];el.style.display=p.z<1?'block':'none';el.style.transform=`translate(${(p.x*.5+.5)*rect.width}px,${(-p.y*.5+.5)*rect.height}px)`;});}
 this.frameTimes.push(performance.now()-start);if(this.frameTimes.length>300)this.frameTimes.shift();}
 capture(){return this.renderer.domElement.toDataURL('image/png');}
 stats(){return {renderMs:this.frameTimes.reduce((s,x)=>s+x,0)/(this.frameTimes.length||1),drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,quality:this.quality,fishCount:this.fish.length};}
 dispose(){this.observer.disconnect();this.controls.dispose();this.school?.dispose();this.fish.forEach(f=>f.dispose());this.garden?.dispose();this.environmentMap?.dispose();this.studio?.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});this.renderer.dispose();this.renderer.forceContextLoss();this.container.replaceChildren();}
}
