/** Data-only contracts shared by the authoring manifest, behavior model and renderer. */
export type EvidenceStatus = 'assumed' | 'measured';
export type Vec3 = [number, number, number];
export interface GeometryData { length:number; width:number; height:number; waterline:number; glassThickness:number; status:EvidenceStatus; note:string; }
export interface FishAppearance { clearanceRadiusFraction:number; form:string; color:string; mark:string; depth:number; thickness:number; tail:number; speed:number; shoal:number; level:number; dorsalOutline:Vec3[]; analOutline:Vec3[]; eyeRadiusFraction:number; finOpacity:number; bodyTaperExponent:number; noseRise:number;ornamentalColors?:string[];femaleDorsalScale:number;femaleAnalScale:number; visualLengthBySex?:{male:number;female:number};floorClearanceFraction?:number;bottomHabitat?:boolean;bottomOffsetCm?:[number,number];pitchLimit?:number;levelSpreadCm?:number;forageChance?:number;surfaceVisit?:{chance:number;clearanceFraction:number;pitchRadians:number;pauseSeconds:[number,number];}; }
export interface SpeciesData { scientificName:string; commonName:string; commonNamePlural:string; totalLengthCm:number; sourceSizeField:string; sourceSizeValue:number|number[]; sizeInterpretation:string; appearance:string; profile:FishAppearance; sourcePlan:string; careSource?:string; }
export interface FishGroup {species:string; count:number; sexRequirement:string; visualSexMix?:('male'|'female')[];}
export interface BotanicalForm {form:string; color:string; height:[number,number]; shoots:[number,number]; rooted:boolean;}
export interface PlantGroup {species:string; quantity:number; unit:string; placement:string; mode:'mixed'|'floating'|'rooted'|'loose'; rootedUnits?:number|null; patchPattern:number[]; profile:BotanicalForm; biomassNote:string;}
export interface NumericRange {low:number; expected:number; high:number; unit:string; method:string;}
export interface HabitatPlan {id:string; name:string; number:number; category?:'alternate'; alternativeStatus?:string; costNote?:string;planUrl?:string;reportUrl?:string|null; country:string; habitat:string; displayHabitat:string; groups:FishGroup[]; plants:PlantGroup[]; fishCount:number; minimumBaseCm:[number,number]; minimumLaneCm:number; substrate:{massLb:number; densityLbPerFt3:number; patchDepthCm:number; patchAreaFraction:number; color:string; note:string;}; decor:unknown[]; startupUsd:number|null; regularStandUsd:number|null; maintenance:NumericRange|null; verdict:string; environment:Record<string,unknown>; unresolved:string[]; planFile:string; reportFile:string; sources:string[]; evidenceLevel:string;}
export interface PlanManifest {schemaVersion:number; source:string; sourceSha256:string; sourceAccessedAt:string; units:'cm'; visualAssumptions:string; ownerProfile:{targetVolume:unknown; upfrontBudgetUsd:number; maintenanceCeilingMinutes:number;}; plans:HabitatPlan[]; species:Record<string,SpeciesData>;}
export interface BehaviorSettings {seed:number; fixedStep:number; maxFrameDelta:number; turnRate:number; speedBlend:number; goalSeconds:[number,number]; hoverChance:number; hoverSeconds:[number,number]; separationStrength:number; wallMargin:number; wallStrength:number; cohesionStrength:number; alignmentStrength:number; wanderStrength:number; obstacleMargin:number; obstacleStrength:number; displayChance:number; displaySeconds:[number,number]; unsexedAppearancePattern:('male'|'female')[];}
